version: '3'

services:
  mysql-db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_USER: 'app'
      POSTGRES_PASSWORD: 'app'
    ports:
      - "54321:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql